### ISSUE TITLE
Wo sind die Daten der 4ten Impfung (Feld Impfschutz zählt immernoch nur bis 3)

### ISSUE THREAD

**Issue by nausgschaut** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#10]
Inwischen sind wir ja beim zweiten Booster angekommen. Bei euch geht es aber bisher immer noch nur bis Impfung 3 (Feld Impfschutz).
Wann wirden die Daten mit debi sein?

**Comment by HannesWuensche** [comment]
Hallo @nausgschaut,

die Frage kam bereits in Issue #8 auf und wir haben die Informationen diesbezüglich ergänzt. 

Mit besten Grüßen
@HannesWuensche
für das für das Team des deutschen Impfmonitorrings | DIM
