### ISSUE TITLE
Daten von vor 2021-07-21 ?

### ISSUE THREAD

**Issue by outa** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#11]
Hallo,

die ältesten Dateien im /Archiv Ordner scheinen vom 7. Juli 2021 zu sein. Gibt es eine Möglichkeit, auch an die älteren Daten ranzukommen?

**Comment by HannesWuensche** [comment]
Hallo @outa,

in den Daten der Landkreise, als auch der Bundesländer, ist die komplette Erfassungshistorie, beginnend mit dem 2020-12-27, abgebildet. Die Daten vor dem 7. Juli 2021 sind somit auch in den aktuellen Daten enthalten. Wir hoffen das hilft ihnen weiter.

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by outa** [comment]
Hallo,

also d.h. ich brauche im Grunde immer nur die aktuellste Datei, und darin sind dann alle Daten enthalten?

**Comment by HannesWuensche** [comment]
Hallo @outa,

so ist es :)

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by outa** [comment]
Ok, vielen Dank!
