### ISSUE TITLE
Mehr Zweitimpfungen als Erstimpfungen in manchen Bundesländern

### ISSUE THREAD

**Issue by stekhn** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#12]
In der [Tabelle der aktuellen Impfquoten](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Impfquoten_COVID-19.csv) übersteigt die Gesamtzahl der Grundimmunisierten (`voll`) die Gesamtzahl der mindestens einmal Geimpften (`min1`). Das gleiche gilt für die daraus errechneten  Impfquoten.

**Gibt es hierfür eine logische Erklärung oder handelt es sich um einen Fehler?** Meinem Verständnis nach, müsste die Zahl der mindestens einmal geimpften Personen immer größer sein als die Zahl der vollständig geimpften Personen. Eine Zweitimpfung ist ja ohne eine Erstimpfung in der Praxis nicht möglich.

Beispiel Bayern, Stand 12. April 2022:

> Impfungen_gesamt_min1: 9732153
> Impfungen_gesamt_voll: 9834378
> Impfquote_gesamt_min1: 74.1
> Impfquote_gesamt_voll: 74.8

Ebenfalls betroffen sind die Bundesländer Schleswig-Holstein, Nordrhein-Westfalen, Baden-Württemberg, Mecklenburg-Vorpommern, Sachsen-Anhalt und Thüringen.

Wenn ich versuche, die Impfquoten aus der [Zeitreihen der Impfserien nach Bundesländern](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv) zu berechnen, bekomme ich ein ähnliches (aber nicht das gleiche) Ergebnis nur, wenn ich bei den Zweitimpfungen jeweils noch die Erstimpfungen mit Janssen dazuzählen.

**Comment by HannesWuensche** [comment]
Hallo @stekhn,

vielen Dank für den Hinweis. Ich habe die Frage an das DIM Team weitergeleitet und wir versuchen zeitnah eine Antwort zu geben.

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by hwuensche** [comment]
Könnte es sein das hier genesene ebenfalls wie Erstgeimpfte angesehen werden?

Gruß
Heiko Wünsche

**Comment by HannesWuensche** [comment]
Hallo @stekhn und @hwuensche,

Wir haben die Dokumentation angepasst und einen Abschnitt eingefügt, der die Hintergründe zu dem oben beschriebenen Phänomen erklärt: [Erklärung zum Merkmal Impfstatus](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland#erkl%C3%A4rung-zum-merkmal-impfstatus). 
Wir hoffen dieser hilft ihnen weiter. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by 4nnabeh** [comment]
Hallo, ich muss trotz der angepassten Dokumentation noch einmal zur Sicherheit nachfragen: Bedeutet das, dass ich aus diesem [Zeitreihen-Datensatz ](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv)nicht die [aktuellen Impfquoten in diesem Datensatz](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Impfquoten_COVID-19.csv) berechnen kann, weil in letzteren Datensatz auch Genesene mit einer Impfung als Grundimmunisierte einfließen, diese im ersteren Datensatz bei Impfserie 2 jedoch nicht vorkommen?

Und ergänzend dazu: Fließen diese Grundimmunisierten (Genesen + 1 Impfung) nicht doch auch indirekt in den [Zeitreihen-Datensatz ](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv) mit ein, nämlich bei der Entscheidung, welche Impfung als erste bzw. zweite Auffrischimpfung gilt?
