### ISSUE TITLE
5. Impfung.

### ISSUE THREAD

**Issue by hwuensche** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#13]
Hallo,
heute taucht zum ersten mal eine Impfung der Impfserie 5 auf. Eine einzige Impfung in ganz Deutschland.
"2022-05-20,07,Comirnaty,5,1"
Wird jetzt schon bis 5 gezählt oder ist das eine Falscheintragung?
Gruß
Heiko Wünsche

**Comment by fischerc-rki** [comment]
Hallo @hwuensche,

vielen Dank für den Hinweis. Die höchste ausgewiesene Impfserie ist 4 und die Ursache für die Ausweisung dieser Impfserie 5 ist ab morgen behoben.

Mit besten Grüßen,
@fischerc-rki 
für das Team RKI | Fachgebiet IT 4 (Development)
