### ISSUE TITLE
Umstellung auf Impf-Abrechnungsdaten der Vertragsärzte für das 4. Quartal 2021

### ISSUE THREAD

**Issue by HannesWuensche** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#14]
Liebe Alle, 

wir möchten über die nächste planmäßige Umstellung im Impfquoten-Monitoring informieren:   

Zum 22.06.2022 werden die COVID-19-Impfdaten aus dem KBV-Meldeportal für das 4. Quartal 2021 mit den Impf-Abrechnungsdaten der Vertragsärzte aus allen 17 KVen ersetzt. Die Impfquoten ändern sich wiederum leicht und geben den Stand der Impfinanspruchnahme in besserer Vollständigkeit und damit genauer wieder.

**Hinweis zur Umstellung der Altersgruppe unter 18 Jahren**

Für den Zeitraum 14.12.-31.12.21 liegen die KV-Abrechnungsdaten der <18-Jährigen nur für die Gesamtaltersgruppe vor, nicht aber weiter differenziert nach 5-11 Jahre und 12-17 Jahre. Daher wurde eine Ersetzung der KBV-Daten durch die KV-Daten für diesen Zeitraum zwar für die Gesamtgruppe <18 Jahre vorgenommen, nicht jedoch für die beiden Einzelaltersgruppen 5-11 und 12-17 Jahre, für die weiterhin die KBV-Daten verwendet wurden. Somit können rund 35.000 Impfungen im Alter <18 Jahren nicht korrekt den beiden Einzelaltersgruppen zugewiesen werden.

**Weiterführende Informationen**

Die aktuellen Daten und weitere Informationen finden Sie dann wie gewohnt unter [www.rki.de/covid-19-impfquoten](https://www.rki.de/covid-19-impfquoten) und in der [Datensatzdokumentation](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Readme.md).

Antworten auf häufig gestellte Fragen zum Impfquotenmonitoring sind unter www.rki.de/covid-19-faq-impfen > Impfquotenmonitoring abrufbar. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by jwildeboer** [comment]
Eine kurze Frage dazu - mit der Umstellung gab es einen gewaltigen Sprung der Impfzahlen für Bayern für den 21.06.2022:

1. Impfung +41732
2. Impfung +49163
3. Impfung +192152
4. Impfung +3987 (was eher normal scheint)

Das kann ja mit der Umstellung nicht viel zu tun haben (weil anderer Zeitraum). Was ist da passiert? Hat Bayern eine andere Datenbereinigung gemacht, die zu diesem Sprung geführt hat?

Jan

**Comment by fischerc-rki** [comment]
Hallo Jan,

die Sprünge in den Anzahlen stammen aus der hier angekündigten Umstellung (Ersetzung KBV-Schnellmeldedaten durch KV-Abrechnungsdaten für Q4 2021). Der [Impfquoten-Datensatz](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland#covid-19-impfquoten) stellt die kumulierten Impfzahlen bis einschließlich dem Vortag dar und beinhaltet mit der Veröffentlichung am 22.06.22 das erste Mal die KV-Abrechnungsdaten für Q4 2021 (siehe Datensatzbeschreibung). 



Mit besten Grüßen,
@fischerc-rki
für das Team RKI | Fachgebiet IT 4 (Development)

**Comment by jwildeboer** [comment]
Danke für die Erklärung. Sieht zwar heftig aus in meiner Tabelle, aber ist dann halt so :)

<img width="677" alt="Screenshot 2022-06-27 at 15 46 34" src="https://user-images.githubusercontent.com/873028/175956933-4133d194-8b84-400e-a234-1dfeeb4e2f45.png">

Einen schönen Tag noch und nochmals Danke!

Jan
