### ISSUE TITLE
Update von heute 2022-09-09 fehlt?

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#15]
Normalerweise gegen 10 Uhr sind die neuen Zahlen da, heute aber nicht. Werden die noch aktualisiert oder wird gerade umgestellt wegen der Omikron Booster?

Jan

**Comment by HannesWuensche** [comment]
Hallo Jan,

vielen Dank für den Hinweis. Leider gab es heute ein Problem mit den Landkreis-Daten. Daher hing die Pipeline bist jetzt.
Wir können die Daten heute nur ohne die Landkreise publizieren. Morgen sollte alles wieder wie gewohnt laufen. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | OpenData
