### ISSUE TITLE
Stimmen die Zahlen heute? Beispiel Bayern.

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#16]
Wenn ich die Ländertabelle nehme (und daraus nur die Zahlen von Bayern betrachte), gab es ggü vorgestern ziemlich gewaltige Sprünge nach oben. Stimmen die Zahlen oder gibt es da irgendwo einen Fehler in der Pipeline?

<img width="156" alt="Screenshot 2022-09-10 at 09 52 32" src="https://user-images.githubusercontent.com/873028/189474515-f5e33d34-bef2-48fa-ba59-5b503a6737c2.png">

Erstimpfungen Bayern
2022-09-07: 9899522
2022-09-09: 9900519
DIFFERENZ: 997 (üblich sind unter 100 Erstimpfungen/Tag)

<img width="163" alt="Screenshot 2022-09-10 at 09 54 28" src="https://user-images.githubusercontent.com/873028/189474545-ae33fd11-4c0a-4a75-8157-9a75e0e7d3c4.png">

Zweitimpfungen Bayern
2022-09-07: 9885816
2022-09-09: 9887474
DIFFERENZ: 1658 (üblich sind unter 100 Zweitimpfungen/Tag)

<img width="155" alt="Screenshot 2022-09-10 at 09 55 45" src="https://user-images.githubusercontent.com/873028/189474575-9faf92da-c199-4663-ae8c-ad411cfefb7b.png">

Drittimpfungen Bayern
2022-09-07: 7734865
2022-09-09: 7740393
DIFFERENZ: 5528 (üblich sind unter 500 Drittimpfungen/Tag)

<img width="158" alt="Screenshot 2022-09-10 at 09 56 20" src="https://user-images.githubusercontent.com/873028/189474587-fdc9d199-5845-4297-a9ab-60c0ef970ce3.png">

Vierttimpfungen Bayern
2022-09-07: 798453
2022-09-09: 815653
DIFFERENZ: 17200 (üblich sind unter 2000 Viertimpfungen/Tag)

Ich hab mal die Zahlen der letzten Tage als Screenshot angehängt. Wobei ich die fehlenden Zahlen vom 2022-09-08 interpoliert habe. Hier nochmal die letzten 30 Tage als Graph.

<img width="423" alt="Screenshot 2022-09-10 at 09 58 33" src="https://user-images.githubusercontent.com/873028/189474650-6d878512-d9c6-469c-9067-6f413cabbbf8.png">

**Comment by fischerc-rki** [comment]
Hallo Jan,

der Sprung in den Gesamtanzahlen ist durch eine Nachmeldung der Impfungen aus Bayern für den Impfzeitraum vom 25.08.2022 bis 07.09.2022  begründet. In diesem Zeitraum gab es Probleme beim Meldeweg aus Bayern über die DIM-Anwendung. Seit dem 10.09.2022 sind die Zahlen wieder vollständig. 

Mit besten Grüßen
@fischerc-rki 
für das Team RKI | Fachgebiet IT 4 (Development)

**Comment by jwildeboer** [comment]
Danke für die Info! Schlussendlich eine gute Nachricht - bessere Impfquote :) Ich schliesse das Issue dann.
