### ISSUE TITLE
Berechnung der Zahl der Grundimmunisierten möglich?

### ISSUE THREAD

**Issue by Data-ntvde** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#18]
Sehr geehrtes RKI-Team,

ich habe eine Frage zum Datensatz [Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv).

Lässt sich aus diesem Datensatz die Zahl der Grundimmunisierten Personen errechnen, die in der csv-Datei [Aktuell_Deutschland_Impfquoten_COVID-19.csv](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Impfquoten_COVID-19.csv) in der Spalte "Impfungen_gesamt_gi" ausgewiesen ist?

Sofern sich dieser Zahl aus "Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv" berechnen lässt: Könnten Sie mir einen Hinweis geben, wie dabei vorzugehen ist?

In der Datei werden in der Spalte "Impfserie" Angaben dazu gemacht, ob es sich um "1: Erstimpfung", "2: Zweitimpfung", "3: erste Auffrischimpfung" oder die "4: zweite Auffrischimpfung" handelt.

Damit lässt sich die Gesamtzahl der "Erstimpfungen", "Zweitimpfungen", ... berechnen, wie sie auch in der werktäglichen RKI-Excel-Tabelle enthalten sind.

Für die Berechnung der Grundimmunisierten muss - wenn ich es richtig verstanden habe - zu den Zweitimpfungen noch ein Teil der Janssen/Jcovden-Impfungen hinzugerechnet werden. Auch in der Readme-Datei wird erläutert, dass ein Teil der Janssen/Jcovden-Impfungen doppelt berücksichtigt wird, dort heißt es:

> Alle bis zum 26.01.2022 im KBV-Portal übermittelten Jcovden-Impfungen mit der Impfserie 2 werden der Impfserie 1 zugeordnet, da diese Impfungen mit hoher Wahrscheinlichkeit tatsächliche Erstimpfungen waren. Für die Impfquotenbestimmung werden diese Impfungen sowohl bei den mindestens einmal Geimpften als auch – der Übermittlung entsprechend - bei den Grundimmunisierten berücksichtigt. Alle ab dem 27.01.2022 übermittelten Impfungen mit Jcovden-Impfstoff werden mit ihrer tatsächlich übermittelten Impfserie ausgewiesen.

Da im Datensatz aber nicht ausgewiesen ist, ob eine Impfung via DIM oder KBV-Portal gemeldet wurde, lässt sich die Zahl der für die Grundimmunisierten relevanten Jcovden-Impfungen nicht bestimmen. Oder doch?

Vielen Dank und schöne Grüße
Christoph Wolf

**Comment by fischerc-rki** [comment]
Hallo Christoph,

korrekt, für die Berechnung der Anzahl an Grundimmunisierten in [Aktuell_Deutschland_Impfquoten_COVID-19.csv](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Impfquoten_COVID-19.csv) (`Impfungen_gesamt_gi`) werden die Jcovden-Impfungen der Vertragsärzte (KBV-Schnellmeldungen bzw. KV-Abrechnungsdaten) bis zum 26.01.202 ebenfalls hinzugezählt, obwohl diese mit `Impfserie` 1 im Datensatz [Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv) ausgewiesen werden. Damit ist die Differenz der Anzahl an Grundimmunisierten aus den beiden genannten Datensätzen (`Impfungen_gesamt_gi` bzw. Summe der `Anzahl` von Datensätzen mit `Impfserie`  2) die gesuchte Anzahl an Jcovden-Impfungen der Vertragsärzte bis zum 26.01.2022.

Mit besten Grüßen
@fischerc-rki
für das Team RKI | Fachgebiet IT 4 (Development)

**Comment by Data-ntvde** [comment]
Hallo @fischerc-rki,

besten Dank für die Erläuterung.  

Ich habe mir die zeitliche Entwicklung dieser Anzahl an Jcovden-Impfungen seit dem Impfdatum 01.05.2022 für alle Bundesländer angeschaut, um zu sehen ob es eventuell noch Korrekturen gibt (was mir sehr unwahrscheinlich schien, da es sich um Impfungen bis zum 26.01.2022 handelt). 

Laut der Auswertung ist die Zahl jedoch für alle Bundesländer seit den am 22.06.2022 (= inklusive Impfungen bis 21.06.2022) veröffentlichten Daten konstant, nachdem es vom Veröffentlichungsdatum 21.06.2022 auf den 22.06.2022 bei allen Bundesländern noch einmal eine Korrektur nach oben gegeben hatte.

Die Korrektur dürfte mit dieser Erklärung in der Readme-Datei zusammengehangen haben, nehme ich an: 

> Ab dem 22.06.2022 gilt: Die KBV-Schnellmeldungen mit Impfungen bis zum Ende des vierten Quartals 2021 (31.12.2021) wurden durch Daten der 17 KVen ersetzt

Künftige Korrekturen dieser Werte sind eher nicht zu erwarten, oder? 

Vielen Dank und schöne Grüße
Christoph

**Comment by fischerc-rki** [comment]
Hallo Christoph,

die Korrektur der Anzahlen nach oben ist in der Tat durch die Ersetzung der KBV-Schnellmeldungen für das vierte Quartal 2021 durch KV-Daten begründet. Korrekturen dieser Werte sind erstmal nicht zu erwarten.

Mit besten Grüßen
@fischerc-rki
für das Team RKI | Fachgebiet IT 4 (Development)

**Comment by Data-ntvde** [comment]
Besten Dank!
