### ISSUE TITLE
Fünft-/Sechst-Impfungen

### ISSUE THREAD

**Issue by edg-stg** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#19]
Aktuell werden in den RKI-Impfdaten nur Impfungen bis zur Viert-Impfung (2. Boosterimpfung) erfasst. Werden demnächst auch noch darüber hinaus gehende Impfserien erfasst? Diese werden u.a. in den niedergelassenen Praxen bereits durchgeführt und erfasst.

**Comment by fischerc-rki** [comment]
Hallo edg-stg,

die fünften udn sechsten Impfungen werden ab morgen ausgewiesen, siehe #20 

Mit besten Grüßen
@fischerc-rki
für das Team RKI | Fachgebiet IT 4 (Development)
