### ISSUE TITLE
Impfquoten nach Bundesland vor 2021-07-22

### ISSUE THREAD

**Issue by knowhatamine** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#23]
Der älteste Release ist vom 22.07.2021. Wo finde ich die Daten für die Impfquoten nach Bundesland für die Zeit vor dem 22.7.2021?

**Comment by HannesWuensche** [comment]
Hallo @knowhatamine,

vielen Dank für den Hinweis. 
Wir halten noch einmal inter Rücksprache und versuchen zeitnah Rückmeldung zu geben. 

Beste Grüße
@HannesWuensche 
für das Team | RKI Open Data

**Comment by knowhatamine** [comment]
Wir schreiben das Jahr 2024 und es sind noch immer keine Impfquoten nach Wohnort auf Basis der Bundesdruckerei-Daten für das Jahr 2021 verfügbar.

Wirklich verblüffend.

**Comment by HannesWuensche** [comment]
Hallo @knowhatamine,

es tut uns leid das das Issue so lange brach lag. 

Leider ist es uns aus Kapazitäts-Gründen nicht möglich gewesen die Tabellen retrospektiv noch zu ergänzen. 
Auch, weil es mit den Daten der Bundesländer und Landkreise möglich ist, diese von Beginn an eigenständig nachzuvollziehen. 

Beste Grüße
@HannesWuensche
für das Team | RKI Open Data
