### ISSUE TITLE
Weihnachtspause in den bayerischen Impfdaten?

### ISSUE THREAD

**Issue by knowhatamine** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#24]
Die Weihnachtspause in den bayerischen Impfdaten in Bayern ist um 6 Wochen verzögert. 

Also der Realität können die bayerischen Daten unmöglich entsprechen.

Sind sie sich dessen bewusst?

**Comment by HannesWuensche** [comment]
Hallo @knowhatamine,

leider ist ihr Hinweis etwas unspezifisch. Könnten sie näher erläutern was sie verwundert, bzw. aufgefallen ist?

Besten Dank
@HannesWuensche 
für das Team RKI | Open Data
