### ISSUE TITLE
Vorerst keine weitere Aktualisierung der Datensätze

### ISSUE THREAD

**Issue by fischerc-rki** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#25]
Liebe Alle,

wir möchten über die nächste planmäßige Umstellung im Impfquoten-Monitoring informieren:

Mit dem Auslaufen der CoronaImpfV am 07. April 2023 wird die tägliche Aktualisierung des COVID-19-Impfquotenmonitorings eingestellt und die Berichterstattung zunächst pausiert. Mit Inkrafttreten der COVID-19-VorsorgeV am 8. April 2023 wird das RKI die Aktualisierungsfrequenz des Impfquotenmonitorings an die Meldefrequenz in der COVID-19-VorsorgeV anpassen und voraussichtlich ab Mai das Update der Impfdaten in angepasster Form und Frequenz wieder aufnehmen. Eine Ankündigung darüber wird dann hier vorab erfolgen.

**Weiterführende Informationen**

Weitere Informationen finden Sie dann wie gewohnt unter [www.rki.de/covid-19-impfquoten](https://www.rki.de/covid-19-impfquoten) und in der [Datensatzdokumentation](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Readme.md).

Antworten auf häufig gestellte Fragen zum Impfquotenmonitoring sind unter [www.rki.de/covid-19-faq-impfen](http://www.rki.de/covid-19-faq-impfen) > Impfquotenmonitoring abrufbar.

Mit besten Grüßen
@fischerc-rki
für das Team RKI | Fachgebiet IT 4 (Development)

**Comment by jwildeboer** [comment]
Wäre gut, daß ganz oben in der README.md zu packen, damit man das sofort sehen kann.
