### ISSUE TITLE
Fehlende Synchronisierung

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#26]
Am 11.05.2023 wurden auf https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html neue Zahlen zu Impfungen auf Landesebene veröffentlicht. Das soll laut der Seite jeden zweiten Dienstag im Monat erfolgen.

Aber die aktualisierten Zahlen wurden hier nicht veröffentlicht. Kann man das korrigieren und in Zukunft automatisieren?

**Comment by HannesWuensche** [comment]
Hallo @jwildeboer,

bezüglich des Themas sind wir derzeit in Abstimmung mit den Kolleg:innen. 
Ich bitte daher noch um etwas Geduld. Wir versuchen Zeitnah eine Rückmeldung zu geben.

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by HannesWuensche** [comment]
Hallo @jwildeboer,

ab nächste Woche soll die Datenbereitstellung dann Syncron auch wieder über Github laufen. 
Die Aktualisierung ist 2-wöchentlich geplant.

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
