### ISSUE TITLE
Sollte es nicht jetzt wöchentliche updates am Dienstag geben?

### ISSUE THREAD

**Issue by Rubber1Duck** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#28]
Sollte es nicht jetzt wöchentliche updates am Dienstag geben? so stand es zumindest in der letzten Ankündigung!

**Comment by Rubber1Duck** [comment]
https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/issues/27#issue-1933078162

> Weiterhin wird die Aktualisierung der Datensätze wöchentlich (jeden Dienstag) erfolgen.

**Comment by RKIOpenData** [comment]
Hallo @Rubber1Duck ,

ja, die Daten sollten eigentlich jeden Dienstag verfügbar sein. Leider hatten wir in den letzten 2 Wochen diverse technische Probleme, weshalb es gehakt hat mit der Veröffentlichung. Ab dieser Woche sollte aber zumindest der Upload auf Github wieder funktionieren. Bei Zenodo gibt es leider weiterhin Probleme. Wir sind aktuell dabei auch für den Zenodo Upload alle Probleme zu beheben, damit möglichst bald wieder alles ordnungsgemäß funktioniert.

viele Grüße
Knut Perseke
für das Team RKI | Open Data
