### ISSUE TITLE
Derzeit keine Aktualisierungen

### ISSUE THREAD

**Issue by Rubber1Duck** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#31]
Hallo RKI Data Team,
gibt es hier keine Aktualisierungen mehr? Ist es eingestellt?

MfG
Peter

**Comment by HannesWuensche** [comment]
Hallo @Rubber1Duck,

vielen Dank für die Nachfrage.
Derzeit gibt es keine Änderung an den Daten, weshalb auch keine Aktualisierung vorgenommen wird. 

Liebe grüße
@HannesWuensche 
RKI | Open Data

**Comment by Rubber1Duck** [comment]
Hallo Hannes,
danke für die Rückmeldung.
wau, keine einzige Impfung in den vergangenen drei Wochen?!

**Comment by RKIOpenData** [comment]
Hallo Rubber1Duck,

wir haben Rückmeldung vom Team des deutschen Impfmonitorings bzgl. des Impfdatensatzes erhalten (haben auch die README entsprechend ergänzt):

> Am 30.06.2024 ist die COVID-19-Vorsorgeverordnung außer Kraft getreten. Mit dem Auslaufen der Verordnung wurden die Meldeportale für die niedergelassene Ärzteschaft zur zeitnahen Übermittlung durchgeführter COVID-19-Impfungen abgeschaltet. Die am 09.07.2024 publizierten Daten repräsentieren den finalen Datenstand des Digitalen Impfquotenmonitorings. Die COVID-19-Impfungen werden künftig wie die anderen Routineimpfungen im Rahmen der [KV-Impfsurveillance](https://doi.org/10.5281/zenodo.12748542) ausgewertet.

Viele Grüße
Simon | RKI Open Data Team
