### ISSUE TITLE
Auswertung der Janssen-Impfungen nach Definition des Paul-Ehrlich-Instituts vom 15.01.2022

### ISSUE THREAD

**Issue by HannesWuensche** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#5]
Liebe User,

Auf der Homepage des Paul-Ehrlich-Instituts wurde die entsprechend der Zulassung geltende Definition, nach der eine Impfstoffdosis des Impfstoffes `Janssen` (Janssen‑Cilag/Johnson & Johnson) zum Nachweis eines vollständigen Impfschutzes ausreicht, mit Wirkung vom 15.01.22 geändert. Nunmehr sind auch beim Janssen‑Cilag/Johnson & Johnson-Impfstoff zwei Impfungen für die Grundimmunisierung vorgesehen. Um diese Änderungen zukünftig auch in den Impfquoten berücksichtigen zu können, müssen jedoch noch Anpassungen in den Meldesystemen und den Auswertungsalgorithmen vorgenommen werden.

Die derzeitig bereitgestellten Daten beziehen sich daher, bezüglich des Impfstoffes `Janssen`, noch auf die bis zum 14.01.22 entsprechend der Zulassung geltende Definition.

Eine die Voraussichtliche Änderung unserer Datenaufbereitung wird innerhalb der nächsten 2 Wochen geschehen und von einem Update der Dokumentaton begleitet. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data und des DIM

**Comment by marcelpauly** [comment]
Ist schon klar,

- wann die Umstellung erfolgen wird,
- ob die Umstellung nur die aktuellen Impfquoten in Aktuell_Deutschland_Impfquoten_COVID-19.csv betrifft oder auch rückwirkend die Zuordnung der Impfserien in Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv und Aktuell_Deutschland_Landkreise_COVID-19-Impfungen.csv,
- ob sich durch die Umstellung auch Tabellenstrukturen verändern werden?

**Comment by HannesWuensche** [comment]
Hallo @marcelpauly,

- leider ist noch nicht klar wann die Umstellung erfolgen wird, wir werden diese aber auf der [Webseite](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html) ankündigen.
- Die Umstellung betrifft alle bereitgestellten Dateien und wird auch Rückwirkend erfolgen. D.h. die komplette Impfhistorie wird neu erstellt. 
- es ist bisher nicht geplant, dass sich die Tabellenstrukturen ändern. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data und des DIM

**Comment by edg-stg** [comment]
gibt es hier Updates?

**Comment by stekhn** [comment]
@HannesWuensche Gibt es neue Infos, wann die Umstellung erfolgen wird?

**Comment by HannesWuensche** [comment]
Liebe Alle,

am am 29.04.2022 erfolgen gebündelt mehrere Umstellungen in der Datenbasis des Impfdaten:
 
- Zum einen werden die zweiten Auffrisch-Impfungen in den Daten ausgewiesen. Die Variablen Impfserie und Impfschutz können nun die Ausprägung ```1``` bis ```4``` annehmen.
- Weiterhin werden die bis zum 30.09.21 an das KBV-Portal übermittelten Impfdaten der niedergelassenen Ärzt*innen durch die vollständigeren KV-Abrechnungsdaten ersetzt und die Zählweise der Janssen-Impfungen mit zwei Impfdosen für die Grundimmunisierung wird angepasst. Dadurch verändern sich die Impfzahlen einmalig leicht, spiegeln den Stand der Impfungen in Deutschland aber genauer wider. 

Diese Änderungen wirken sich auf die in bereitgestellten Datenformate aus:: 

**Aktuell_Deutschland_Impfquoten_COVID-19_Beispiel-Umstellung.csv**
- Suffix "_boost" wird durch "boost_1" ersetzt
- Suffix "_boost_2" wird hinzugefügt
- Suffix "_voll" wird durch "_gi" (grundimmunisiert) ersetzt
- zukünftig wird nicht mehr von "vollständigem" Schutz sondern "grundimmunisiert" gesprochen

**Aktuell_Deutschland_Landkreise_COVID-19-Impfungen_Beispiel-Umstellung.csv**
- "Impfschutz" nimmt die Werte ```1``` bis ```4``` an

**Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen_Beispiel-Umstellung.csv**
- "Impfdosis" nimmt die Werte ```1``` bis ```4``` an


Eine ausführliche Beschreibung der Datenquellen, der Aufbereitung der Daten, der Variablen sowie der Metadaten können in der angepassten Datensatzdokumentation (Readme.md) nachgelesen werden. 

Mit besten Grüßen
@HannesWuensche 
für das für das Team des deutschen Impfmonitorrings | DIM

**Comment by HannesWuensche** [comment]
Liebe Alle, 

die Umstellung ist soeben erfolgt.

Mit besten Grüßen
@HannesWuensche
für das Team des deutschen Impfmonitorrings | DIM

**Comment by marcelpauly** [comment]
Die Suffixe bleiben jetzt bei _boost1 und _boost2 und werden nicht (wie oben angekündigt) noch in _boost_1 und _boost_2 geändert, oder?

**Comment by HannesWuensche** [comment]
Hallo @marcelpauly,

ja, die Suffixe bleiben bei  "_boost1" und "_boost2". 
Der zusätzliche Unterstrich in der Ankündigung ist ein Fehler von mir gewesen. Ich bitte um Entschuldigung. 

Mit besten Grüßen
@HannesWuensche
für das Team des deutschen Impfmonitorrings | DIM
