### ISSUE TITLE
Anbindung ZÄ nach §20b IFSG

### ISSUE THREAD

**Issue by Nilihasi** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#6]
Durch den Beschluss der Ministerpräsidenten vom 02.12.21 sollen zukünftig auch Zahnärzte Impfungen durchführen.

Die Zahnarztpraxen sind ebenso wie die Arztpraxen an die TI angeschlossen und verwenden eigene SMC-Bs zur Authentifizierung. 

Wann erfolgt die Anbindung ?

**Comment by HannesWuensche** [comment]
Hallo @Nilihasi,

Zahnärzte sind derzeit noch keine eigenständigen Leistungserbringer im Sinne der Coronavirus-Impfverordnung. Wir können Sie also leider nicht direkt anbinden. Derzeit wird an zentralen Wegen für die Anbindung von Zahnärzten gearbeitet. Weitere Informationen dazu liegen uns aber aktuell nicht vor. Für eine Anbindung Ihrer Zahnarztpraxis bitten wir daher noch um etwas Geduld. 

Es bestünde gemäß Coronavirus-Impfverordnung für Sie derzeit grundsätzlich die Möglichkeit, als durch das Land beauftragter Dritter in die Impfkampagne einbezogen und somit an DIM angebunden zu werden. In diesem Fall wenden Sie sich bitte an Ihre zuständige Landesbehörde.

Darüber hinaus weisen wir darauf hin, dass auch Zahnärzte unter bestimmten Bedingungen bereits heute beispielsweise in Impfzentren COVID-19-Impfungen verabreichen können.

Vielen Dank für Ihr Verständnis.

Mit freundlichen Grüßen
DIM-Koordination am RKI

**Comment by HannesWuensche** [comment]
Hallo @Nilihasi ,

Zahnärzte sind derzeit noch keine eigenständigen Leistungserbringer im Sinne der Coronavirus-Impfverordnung. Wir können Sie also leider nicht direkt anbinden. Derzeit wird an zentralen Wegen für die Anbindung von Zahnärzten gearbeitet. Weitere Informationen dazu liegen uns aber aktuell nicht vor. Für eine Anbindung Ihrer Zahnarztpraxis bitten wir daher noch um etwas Geduld. 

Es bestünde gemäß Coronavirus-Impfverordnung für Sie derzeit grundsätzlich die Möglichkeit, als durch das Land beauftragter Dritter in die Impfkampagne einbezogen und somit an DIM angebunden zu werden. In diesem Fall wenden Sie sich bitte an Ihre zuständige Landesbehörde.

Darüber hinaus weisen wir darauf hin, dass auch Zahnärzte unter bestimmten Bedingungen bereits heute beispielsweise in Impfzentren COVID-19-Impfungen verabreichen können.

Vielen Dank für Ihr Verständnis.

Mit freundlichen Grüßen
DIM-Koordination am RKI
