### ISSUE TITLE
Vierte Impfung und neuer Impfstoff Novavax in den Daten?

### ISSUE THREAD

**Issue by schmdjhnnsn** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#8]
Liebes Datenteam des RKI, 
wann ist damit zu rechnen, dass in der [Variablenausprägung](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland#variablenauspr%C3%A4gungen) die weiteren Merkmale 

- x Impfstoff: "Nuvaxovid: Novavax"
- xx Impfserie: "4: Vierte Impfung"
aufgenommen werden?

![image](https://user-images.githubusercontent.com/46447088/155729644-23c78254-a833-4064-bc31-21d7280cd2a6.png)

Vielen Dank im Voraus.

@HannesWuensche @RKIForschungsdatenmanagement @RKIOpenData

**Comment by HannesWuensche** [comment]
Hallo @schmdjhnnsn,

- die Impfungen mit `Novavax`: Novavax sind seit gestern in den Daten enthalten, die Dokumentation ist entsprechend angepasst
- bezüglich 4ter Impfungen, können wir leider noch keine genaue Angabe machen, wann diese in die Daten aufgenommen werden

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data und des DIM

**Comment by doubtmeister** [comment]
Sind Viertimpfungen denn derzeit als Auffrischungsimpfung in den Daten enthalten, oder werden diese gar nicht mitgezählt?

**Comment by HannesWuensche** [comment]
Hallo @doubtmeister,

derzeit werden 4te Impfungen in der Auswertung nicht mit berücksichtigt. Also auch nicht als Auffrischungsimpfungen mitgezählt.

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data und des DIM

**Comment by doubtmeister** [comment]
Das bedeutet also, die Gesamtzahl der tatsächlichen Impfungen ist (u.U. erheblich) höher als die Gesamtanzahl der Impfungen in den Datensätzen? Lässt sich die Gesamtzahl der tatsächlichen Impfungen irgendwo herausfinden?

Bei dieser Gelegenheit übrigens herzlichen Dank für das Bereitstellen und Pflegen der "Open Data" bei Github!

**Comment by edg-stg** [comment]
Zumindest die Viert-Impfungen in ärztlichen Praxen veröffentlichen wir (aufbereitet) im Impfindex der KBV/des Zi:
https://www.zidatasciencelab.de/covidimpfindex/
Aus dem Plot "Impfungen nach Einrichtung und Impfserie" können diese heruntergeladen werden.

**Comment by HannesWuensche** [comment]
Liebe Alle,

am am 29.04.2022 erfolgen gebündelt mehrere Umstellungen in der Datenbasis des Impfdaten:
 
- Zum einen werden die zweiten Auffrisch-Impfungen in den Daten ausgewiesen. Die Variablen Impfserie und Impfschutz können nun die Ausprägung ```1``` bis ```4``` annehmen.
- Weiterhin werden die bis zum 30.09.21 an das KBV-Portal übermittelten Impfdaten der niedergelassenen Ärzt*innen durch die vollständigeren KV-Abrechnungsdaten ersetzt und die Zählweise der Janssen-Impfungen mit zwei Impfdosen für die Grundimmunisierung wird angepasst. Dadurch verändern sich die Impfzahlen einmalig leicht, spiegeln den Stand der Impfungen in Deutschland aber genauer wider. 

Diese Änderungen wirken sich auf die in bereitgestellten Datenformate aus:: 

**Aktuell_Deutschland_Impfquoten_COVID-19_Beispiel-Umstellung.csv**
- Suffix "_boost" wird durch "boost_1" ersetzt
- Suffix "_boost_2" wird hinzugefügt
- Suffix "_voll" wird durch "_gi" (grundimmunisiert) ersetzt
- zukünftig wird nicht mehr von "vollständigem" Schutz sondern "grundimmunisiert" gesprochen

**Aktuell_Deutschland_Landkreise_COVID-19-Impfungen_Beispiel-Umstellung.csv**
- "Impfschutz" nimmt die Werte ```1``` bis ```4``` an

**Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen_Beispiel-Umstellung.csv**
- "Impfdosis" nimmt die Werte ```1``` bis ```4``` an


Eine ausführliche Beschreibung der Datenquellen, der Aufbereitung der Daten, der Variablen sowie der Metadaten können in der angepassten Datensatzdokumentation (Readme.md) nachgelesen werden. 

Mit besten Grüßen
@HannesWuensche 
für das für das Team des deutschen Impfmonitorrings | DIM

**Comment by HannesWuensche** [comment]
Liebe Alle,

die Umstellung ist soeben erfolgt. 

Mit Besten Grüße
@HannesWuensche 
für das Team des deutschen Impfmonitorrings | DIM
