### ISSUE TITLE
Differenz bei Impfungen gesamt zwischen RKI-csv und RKI-Excel

### ISSUE THREAD

**Issue by Data-ntvde** [robert-koch-institut/COVID-19-Impfungen_in_Deutschland#9]
Hallo Herr Wünsche,

ich hatte es so verstanden, dass die csv-Datei https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/master/Aktuell_Deutschland_Impfquoten_COVID-19.csv im Prinzip das Tab "Impfquote_bundesweit_Alter" in der werktäglich [erstellten RKI-Excel-Datei](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquotenmonitoring.xlsx?__blob=publicationFile)  abbilden soll.

Allerdings gibt es dort Unterschiede bei der Angabe der Gesamtzahl der verabreichten Impfungen.

In der Excel-Datei vom 02.03.2022 sind es insgesamt 170.058.529 verabreichte Impfungen - in der csv-Datei sind es hingegen 170.059.427 Impfungen_gesamt.

Die Differenz ist zwar nur gering, aber können Sie mir sagen, woher diese unterschiedliche Gesamtzahl kommt? 

Die in der Excel-Datei genannte Zahl an Gesamtimpfungen ergibt sich auch, wenn man die Daten vom Impfdashboard ([tsv-Datei](https://impfdashboard.de/static/data/germany_vaccinations_timeseries_v2.tsv)) aggregiert und dabei die Erstimpfungen mit Johnsen zur Gruppe "Impfungen_gesamt_voll" addiert. Der Wert von 170.058.529 ist damit für mich nachvollziehbar - der in der csv genannte, leicht höhere Gesamtwert hingegen nicht.

Zumal die Angaben zu "Impfungen_gesamt_min1", "Impfungen_gesamt_voll" und zu "Impfungen_gesamt_boost" in Excel und csv übereinstimmen.

Vielen Dank und schöne Grüße
Christoph Wolf

**Comment by HannesWuensche** [comment]
Lieber Herr Wolf,

vielen Dank für den Hinweis. Ich habe die Frage an das DIM Team weitergeleitet und wir versuchen zeitnah eine Antwort zu geben. 

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by fischerc-rki** [comment]
Lieber Herr Wolf,

der Fehler wurde inzwischen behoben und seit der Veröffentlichung vom 05.03.2022 ist keine Differenz mehr vorhanden.

Mit besten Grüßen,
Constantin Fischer
@fischerc-rki 
RKI | IT 4 - Development
